#!/bin/bash

# Add this at the begining of all scripts.
if [ -f "include/startup.sh" ]; then
    . include/startup.sh
elif [ -f "../include/startup.sh" ]; then
    . ../include/startup.sh
fi

checkTagExist php-fpm.success

phpVersion=$(php -v | head -n 1 | cut -d " " -f 2 | cut -f1-2 -d".")


echo "Set php fpm socket" | log
sed -i 's/listen = 127.0.0.1:9000/listen = \/run\/php\/php-fpm.sock/g' /etc/php/$phpVersion/fpm/pool.d/www.conf

echo "Edit Apache VHOST conf" | log
sed -i 's/SetHandler "proxy:fcgi:\/\/127.0.0.1:9000"/SetHandler "proxy:unix:\/var\/run\/php\/php-fpm.sock|fcgi:\/\/localhost\/"/g' /etc/apache2/sites-available/000-default.conf

echo "Enable php-fpm in default-ssl.conf" | log
sed -i '22 a <Directory \/var\/www\/html>\n  Options -Indexes +FollowSymLinks +MultiViews\n  AllowOverride All\n  Require all granted\n<\/Directory>\n\n<FilesMatch \.php$>\n  SetHandler "proxy:unix:\/var\/run\/php\/php-fpm.sock|fcgi:\/\/localhost\/"\n<\/FilesMatch>\n' /etc/apache2/sites-available/default-ssl.conf


exit 0
