#!/bin/bash

if [ -f "include/startup.sh" ]; then
    . include/startup.sh
elif [ -f "../include/startup.sh" ]; then
    . ../include/startup.sh
fi

echo "pull engentron configs from github" | log
mv /etc/nginx/nginx.conf /etc/nginx/nginx.conf.orig
wget https://raw.githubusercontent.com/engintron/engintron/master/nginx/nginx.conf -O /etc/nginx/nginx.conf
wget https://raw.githubusercontent.com/engintron/engintron/master/nginx/common_http.conf -O /etc/nginx/common_http.conf
wget https://raw.githubusercontent.com/engintron/engintron/master/nginx/common_https.conf -O /etc/nginx/common_https.conf
wget https://raw.githubusercontent.com/engintron/engintron/master/nginx/custom_rules -O /etc/nginx/custom_rules
wget https://raw.githubusercontent.com/engintron/engintron/master/nginx/proxy_params_common -O /etc/nginx/proxy_params_common
wget https://raw.githubusercontent.com/engintron/engintron/master/nginx/proxy_params_dynamic -O /etc/nginx/proxy_params_dynamic
wget https://raw.githubusercontent.com/engintron/engintron/master/nginx/proxy_params_static -O /etc/nginx/proxy_params_static

echo "configure cloud-xip.io domain in Nginx default.conf|default_https.conf" | log
sed -i 's/user nginx/user www-data/g' /etc/nginx/nginx.conf
sed -i '56 a set $PROXY_DOMAIN_OR_IP "127.0.0.1";' /etc/nginx/custom_rules

echo "create info.php files" | log
touch /etc/www/html/info.php
chown www-data:www-data /etc/www/html/info.php
echo "<?php phpinfo(); ?>" > /var/www/html/info.php

echo "create default.conf files" | log
touch /etc/nginx/conf.d/default.conf
touch /etc/nginx/conf.d/default_https.conf
mkdir -p /var/cache/nginx


echo "
# /**
#  * @version    1.13.0
#  * @package    for cPanel/WHM
#  * @author     Fotis Evangelou (https://kodeka.io)
#  * @url        https://engintron.com
#  * @copyright  Copyright (c) 2018 - 2019 Kodeka OÜ. All rights reserved.
#  * @license    GNU/GPL license: https://www.gnu.org/copyleft/gpl.html
#  */

server {
    #listen 80 default_server;
    listen [::]:80 default_server ipv6only=off;

    server_name exampleip www.exampleip;
    return  301 https://\$server_name\$request_uri;
    # deny all; # DO NOT REMOVE OR CHANGE THIS LINE - Used when Engintron is disabled to block Nginx from becoming an open proxy

    # Set the port for HTTP proxying
    set \$PROXY_TO_PORT 8080;

    include common_http.conf;
}
" > /etc/nginx/conf.d/default.conf

echo "
# /**
#  * @version    1.13.0
#  * @package    Engintron for cPanel/WHM
#  * @author     Fotis Evangelou (https://kodeka.io)
#  * @url        https://engintron.com
#  * @copyright  Copyright (c) 2018 - 2019 Kodeka OÜ. All rights reserved.
#  * @license    GNU/GPL license: https://www.gnu.org/copyleft/gpl.html
#  */

# Default definition block for HTTPS
server {

    listen 443 ssl http2 default_server;
    #listen [::]:443 ssl http2 default_server;
    server_name exampleip www.exampleip;

    ssl_certificate      /etc/letsencrypt/live/exampleip/fullchain.pem;
    ssl_certificate_key  /etc/letsencrypt/live/exampleip/privkey.pem;

    include common_https.conf;
}

##### Additional Domains #####
#server {
#
#    listen 443 ssl http2;
#    server_name example.com www.example.com;
#
#    ssl_certificate      /etc/ssl/certs/exampleip;
#    ssl_certificate_key  /etc/ssl/private/exampleip;
#
#    include common_https.conf;
#}
" > /etc/nginx/conf.d/default_https.conf

echo "Set domain name" | log
sed -i "s/exampleip/${CWM_DOMAIN}/g" /etc/nginx/conf.d/default.conf
sed -i "s/exampleip/${CWM_DOMAIN}/g" /etc/nginx/conf.d/default_https.conf


echo "Generate dhparam for engintron" | log
if [ ! -d /etc/ssl/engintron ]; then
    mkdir -p /etc/ssl/engintron
fi

openssl dhparam -out /etc/ssl/certs/dhparam.pem 2048


service nginx restart

tagScript success

exit 0
